name: Vercel Workflow

# Trigger
on: 
  push:
    branches:
    - release/*

# Jobs
jobs:
  # Job name
    vercel-workflow-filter:
      runs-on: ubuntu-latest

    # List of steps to perform task
      steps:
      - name: Echo the date
        run: echo "The current time and date in Github is $(date)"
      - name: Echo the branch name
        run: echo "current branch - ${{ github.ref-name }}"
      - name: Checkout the branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Deplay to Vercel
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJ_ID }}
          vercel-args: "--prod"