name: Vercel Workflow

# Trigger
on: 
  push:
    branches:
    - release/*

# Jobs
jobs:
  # Job name
    vercel-workflow-filter:
      runs-on: ubuntu-latest

    # List of steps to perform task
      steps:
      - name: Echo the date
        run: echo "The curren time and date in Github is $(date)"
      - name: Echo the branch name
        run: echo "current branch - ${{ github.ref-name }}"
      - name: Checkout the branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}